export const comments = [
 {
  postId: 1,
  id: 1,
  name: "id labore ex et quam laborum",
  email: "Eliseo@gardner.biz",
  body: "laudantium enim quasi est quidem magnam voluptate ipsam eos tempora quo necessitatibus dolor quam autem quasi reiciendis et nam sapiente accusantium",
 },
 {
  postId: 1,
  id: 2,
  name: "quo vero reiciendis velit similique earum",
  email: "Jayne_Kuhic@sydney.com",
  body: "est natus enim nihil est dolore omnis voluptatem numquamet omnis occaecati quod ullam atvoluptatem error expedita pariaturnihil sint nostrum voluptatem reiciendis et",
 },
 {
  postId: 1,
  id: 3,
  name: "odio adipisci rerum aut animi",
  email: "Nikita@garfield.biz",
  body: "quia molestiae reprehenderit quasi aspernatur occaecati aliquam eveniet laudantiumnis quibusdam delectus saepe quia accusamus maiores nam estcum et ducimus et vero voluptates excepturi deleniti ratione",
 },
 {
  postId: 1,
  id: 4,
  name: "alias odio sit",
  email: "Lew@alysha.tv",
  body: "non et atqueoccaecati deserunt quas accusantium unde odit nobis qui voluptatemquia voluptas consequuntur itaque doloret qui rerum deleniti ut occaecati",
 },
 {
  postId: 1,
  id: 5,
  name: "vero eaque aliquid doloribus et culpa",
  email: "Hayden@althea.biz",
  body: "harum non quasi et rationetempore iure ex voluptates in rationeharum architecto fugit inventore cupiditatevoluptates magni quo et",
 },
 {
  postId: 2,
  id: 6,
  name: "et fugit eligendi deleniti quidem qui sint nihil autem",
  email: "Presley.Mueller@myrl.com",
  body: "doloribus at sed quis culpa deserunt consectetur qui praesentiumccusamus fugiat dictavoluptatem rerum ut voluptate autemvoluptatem repellendus aspernatur dolorem in",
 },
 {
  postId: 2,
  id: 7,
  name: "repellat consequatur praesentium vel minus molestias voluptatum",
  email: "Dallas@ole.me",
  body: "maiores sed dolores similique labore et inventore etuasi temporibus esse sunt id и etos voluptatem aliquamliquid ratione corporis molestiae mollitia quia et magnam dolor",
 },
 {
  postId: 2,
  id: 8,
  name: "et omnis dolorem",
  email: "Mallory_Kunze@marie.org",
  body: "ut voluptatem corrupti velitd voluptatem maiorest nisi velit vero accusamus maiores quia aliquid ullam eaque",
 },
 {
  postId: 2,
  id: 9,
  name: "provident id voluptas",
  email: "Meghan_Littel@rene.us",
  body: "sapiente assumenda molestiae atqueipisci laborum distinctio aperiam et ab ut omnist occaecati aspernatur odit sit rem expeditauas enim ipsam minus",
 },
 {
  postId: 2,
  id: 10,
  name: "eaque et deleniti atque tenetur ut quo ut",
  email: "Carmen_Keeling@caroline.name",
  body: "voluptate iusto quis nobis reprehenderit ipsum amet nullauia quas dolores velit et nonut quia necessitatibusostrum quaerat nulla et accusamus nisi facilis",
 },
];